version: '3.8'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        environment:
            - REDIS_URL=redis://redis:6379
    redis:
        image: 'redis:alpine'
